name: Lab7 - Build Docker Toolchain

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # cần để push image lên GitHub Container Registry (GHCR)

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login vào GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: |
            OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
            IMAGE_NAME=ghcr.io/$OWNER/bbb-toolchain:latest
            docker build -t $IMAGE_NAME .
            echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME
